[package]
name = "wc"
version = "0.1.0"
description = "Print newline, word, and byte counts for each file"
authors = ["Mauri de Souza Nunes <mauri870@gmail.com>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
